import { gql, useMutation } from "@apollo/client";
import { useForm } from "react-hook-form";
import { useLocation, useHistory } from "react-router-dom";
import {useState, useEffect} from "react";
import { faTimesCircle } from "@fortawesome/free-regular-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import PageTitle from "../components/PageTitle";
import { InputDiv, ClearIcon, Input, Label} from "../components/InputElements";
import Modal from "../components/ModalElements";
import InputError from "../components/InputError";
import AuthLayOut from "../components/AuthLayOut";
import Button from "../components/Button";
import DaumPostcode from "react-daum-postcode";
import MessageBox from "../components/MessageBox";